apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  workspaces:
    - name: pipeline-workspace
  params:
    - name: repo-url
      type: string
      default: "https://github.com/Rodney-hub-1978/devops-capstone-project.git"
    - name: branch
      type: string
      default: "main"
    - name: image-name
      type: string
      default: "my-app"
    - name: image-tag
      type: string
      default: "latest"
  tasks:
    # Exercise 1-2, 6: Clone repository
    - name: clone
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: pipeline-workspace
      params:
        - name: url
          value: "$(params.repo-url)"
        - name: revision
          value: "$(params.branch)"
    
    # Exercise 3: Lint code
    - name: lint
      taskRef:
        name: flake8
      workspaces:
        - name: source
          workspace: pipeline-workspace
      params:
        - name: image
          value: "python:3.9-slim"
        - name: args
          value:
            - "--count"
            - "--max-complexity=10"
            - "--max-line-length=127"
            - "--statistics"
      runAfter:
        - clone
    
    # Exercise 4-5: Run tests (in parallel with lint)
    - name: tests
      workspaces:
        - name: source
          workspace: pipeline-workspace
      taskRef:
        name: nose
      params:
        - name: database_uri
          value: "sqlite:///test.db"
        - name: args
          value: "-v --with-spec --spec-color"
      runAfter:
        - clone
    
    # Exercise 7: Build task (runs after lint AND tests complete)
    - name: build
      taskRef:
        name: build
      workspaces:
        - name: source
          workspace: pipeline-workspace
      params:
        - name: image
          value: "$(params.image-name)"
        - name: tag
          value: "$(params.image-tag)"
        - name: dockerfile
          value: "Dockerfile"
      runAfter:
        - lint
        - tests
    
    # Exercise 8: Deploy task (runs after build)
    - name: deploy
      taskRef:
        name: deploy
      workspaces:
        - name: source
          workspace: pipeline-workspace
      params:
        - name: image
          value: "$(params.image-name):$(params.image-tag)"
      runAfter:
        - build
